### ISSUE TITLE
handle null in actual_ship_date

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/errata-tool#113]
We end up crashing on this particular advisory in stage:

```
>>> from errata_tool import ErrataConnector, Erratum
>>> Erratum(errata_id=36334)
<errata_tool.erratum.Erratum object at 0x7f71fc3f6e50>
>>> ErrataConnector._url= 'https://errata.stage.engineering.redhat.com'
>>> Erratum(errata_id=41043)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python2.7/site-packages/errata_tool/erratum.py", line 125, in __init__
    self._fetch(kwargs['errata_id'])
  File "lib/python2.7/site-packages/errata_tool/erratum.py", line 229, in _fetch
    d = time.strptime(str(d), '%Y-%m-%dT%H:%M:%SZ')
  File "/usr/lib64/python2.7/_strptime.py", line 478, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data 'None' does not match format '%Y-%m-%dT%H:%M:%SZ'
time data 'None' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

@lcarva pointed out that the advisory in stage has an `actual_ship_date` as `null`

**Comment by yazug** [comment]
pull #178 and pull #183  should have resolved this issue
