### ISSUE TITLE
Adding build failed into erratum

### ISSUE THREAD

**Issue by phracek** [red-hat-storage/errata-tool#130]
In case erratum already has build, even with the same build.
I would prefer to raise an exception like ErratumBuildExists
~~~
 [2018-11-29 09:13:24,376: INFO/ForkPoolWorker-1] task.ferdinand.errata[e9347bac-7344-4423-84a2-b20345528e63]: {
   "level": "INFO",
   "message": "Adding build 1065956 into errata 43156 with release 357",
   "task": "task.ferdinand.errata",
   "time": "2018-11-29 09:13:24.376842"
 }
 [2018-11-29 09:13:25,636: ERROR/ForkPoolWorker-1] Task task.ferdinand.errata[e9347bac-7344-4423-84a2-b20345528e63] raised unexpected: ErrataException('Erratum 43156: Incorrect parameters: Build rsyslog-docker-7.4rcerven-12 already added to errata id 43156 (for Product Version EXTRAS-7-RHEL-7). Changing the archive type to a build already added is not supported via the API. Please remove the build and add it again.',)
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
     R = retval = fun(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
     return self.run(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/ferdinand/tasks.py", line 23, in create_errata
     return self.errata(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/ferdinand/ferdinand_errata.py", line 35, in errata
     erratum_url = errata.create_errata()
   File "/usr/local/lib/python3.6/site-packages/ferdinand/errata.py", line 193, in create_errata
     return self.update_errata()
   File "/usr/local/lib/python3.6/site-packages/ferdinand/errata.py", line 144, in update_errata
     self._add_builds()
   File "/usr/local/lib/python3.6/site-packages/ferdinand/errata.py", line 49, in _add_builds
     file_type={self.build_id: ['tar']})
   File "/usr/local/lib/python3.6/site-packages/errata_tool/erratum.py", line 684, in addBuilds
     return self.addBuildsDirect(buildlist, release, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/errata_tool/erratum.py", line 664, in addBuildsDirect
     self._processResponse(r)
   File "/usr/local/lib/python3.6/site-packages/errata_tool/connector.py", line 242, in _processResponse
     raise ErrataException(err_msg)
 errata_tool.exception.ErrataException: Erratum 43156: Incorrect parameters: Build rsyslog-docker-7.4rcerven-12 already added to errata id 43156 (for Product Version EXTRAS-7-RHEL-7). Changing the archive type to a build already added is not supported via the API. Please remove the build and add it again.
~~~

**Comment by phracek** [comment]
This is already solved by PR #129
