### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool(host='errata.devel.redhat.com', port=443): Max retries exceeded with url

### ISSUE THREAD

**Issue by shiywang** [red-hat-storage/errata-tool#158]
```
➜  ~ elliott --group=openshift-3.9 find-bugs --id 1698136 --id 1693320  --id 1613280 --id 1686266 --id 1693036 --id 1686947 --id 1420235 --id 1678372 --id 1463717 --id 1550015 --id 1688642 --id 1508107 --id 1429788 --id  1645143 --add 41339
/home/shiywang/.config/elliott/settings.yaml
2019-04-17 11:28:40,572 INFO Data clone directory already exists, checking commit sha
2019-04-17 11:28:41,980 INFO https://github.com/openshift/ocp-build-data.git is already cloned and latest
/usr/lib/python2.7/site-packages/elliottlib/runtime.py:143: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  tmp_config = Model(yaml.load(group_yml.format(**replace_vars)))
2019-04-17 11:28:42,039 INFO Using branch from group.yml: rhaos-3.9-rhel-7
Adding 14 bugs to advisory 41339
Traceback (most recent call last):
  File "/usr/bin/elliott", line 854, in <module>
    main()
  File "/usr/bin/elliott", line 843, in main
    cli(obj={})
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/elliott", line 425, in find_bugs
    advs.commit()
  File "/usr/lib/python2.7/site-packages/errata_tool/erratum.py", line 946, in commit
    self._write()
  File "/usr/lib/python2.7/site-packages/errata_tool/erratum.py", line 885, in _write
    r = self._put(url, data=pdata)
  File "/usr/lib/python2.7/site-packages/errata_tool/connector.py", line 189, in _put
    verify=self.ssl_verify)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='errata.devel.redhat.com', port=443): Max retries exceeded with url: /api/v1/erratum/41339 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
```
our elliott using this lib for querying errata, not sure if there's some limitation on connections of errata servers? but report this bug on here, hope someone could tell me who should I ask for..

**Comment by ktdreyer** [comment]
It's hard for me to know if this is a server-side issue or a client-side issue.

Does it work if you re-run it?

Does `curl --negotiate -u : -I https://errata.devel.redhat.com/api/v1/erratum/41339` work on this same system, or does it show an SSL error?

What is your base operating system? If it's RHEL 7, what minor release? What is your version of openssl-libs?

**Comment by yazug** [comment]
When I have seen this in the past it is Infra related.  Usually connectivity or load on the servers.  Does it happen often?

**Comment by ktdreyer** [comment]
[osbs-client](https://github.com/containerbuildsystem/osbs-client) uses `from requests.packages.urllib3.util import Retry`. Maybe we could do the same in our requests session (see also https://github.com/red-hat-storage/errata-tool/pull/146)

**Comment by ktdreyer** [comment]
I guess the code looks something like this

```python
import requests
from requests.packages.urllib3.util import retry
session = requests.Session()
adapter = requests.adapters.HTTPAdapter(max_retries=retry.Retry())
session.mount('https://', adapter)
response = session.get(...)
```
