### ISSUE TITLE
Traceback when fetching errata info

### ISSUE THREAD

**Issue by dhodovsk** [red-hat-storage/errata-tool#227]
After recent errata_tool update, errata_tool.Erratum._fetch method throws an error:
```
>>> from errata_tool import Erratum
>>> e = Erratum(errata_id=93249)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/errata_tool/erratum.py", line 130, in __init__
    self._fetch(kwargs['errata_id'])
  File "/usr/local/lib/python3.10/site-packages/errata_tool/erratum.py", line 271, in _fetch
    self._product = advisory
```

**Comment by hluk** [comment]
This is probably related to breaking change in `/advisory/{id}.json` in the just released Errata Tool.

**Comment by yazug** [comment]
I think the breaking change was rolled back in ET

**Comment by dhodovsk** [comment]
Correct, it works now, thank you :)

**Comment by ktdreyer** [comment]
I think this was resolved in RHELWF-6417.

Longer-term: in RHELWF-5989 Jon Orris asked us to try to move away from the legacy `/advisory/<id>.json` endpoint and do everything via `/api/v1/erratum/<id>`

**Comment by yazug** [comment]
If I recall correctly the user information is one of the difficult parts that wasn't in api/v1 but there may be other parts that are pulled from there as well
